Implement fallback to deviceinfo if getprop fails
ubports/system-image pull request #11
Opened 2020-03-23 20:38 UTC by Flohack74

This PR was remade to have the right branch name. This is needed for Non-Android phones that do not have getprop implemented. Should fix #9

2020-03-24 20:26 UTC, nanu-c commented
Works on my side, it's also verified with push server and it needs a reboot to pick up new device name

2020-03-26 19:35 UTC, mariogrip commented
A better idea would be to replace it fully with deviceinfo and place it into the xenial_-_edge_-_wayland branch

2020-03-26 20:53 UTC, nanu-c commented
But then we have again multiple branches instead of 1 master branch or is the xenial_-edge-_wayland the one and only master and this here is going to be dropped?

2020-03-26 23:28 UTC, Flohack74 commented
@nanu-c Marius offered this as a possibiliity to get it merged before OTA-12 is released since we are freezing there (as much as we can, since still things gets merged to some repos it seems)

2020-08-28 06:40 UTC, Flohack74 commented
Hmm what we are going to do with this? I can see Pinephones now reporting correctly with deviceinfo tag. Shall we close this @mariogrip

2020-12-18 21:33 UTC, dobey requested changes

2020-12-18 21:33 UTC, dobey commented on systemimage/device.py
> +        except:
Please do not use blanket exceptions. Instead this should be `except CalledProcessError:` to only catch the failure to run getprop.

2020-12-18 21:33 UTC, dobey commented on systemimage/device.py
> +            except:
Another blanket except clause. Please catch the appropriate `CalledProcessError` instead.

2021-08-19 16:50 UTC, peat-psuwit commented
Migrated to GitLab.

https://gitlab.com/ubports/core/system-image/-/merge_requests/11

2021-08-19 16:50 UTC, closed without merging